/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tempeture_coverter;

/**
 *
 * @author gunawar-cs19001
 */
public class tempeture_converter extends javax.swing.JFrame {

    /**
     * Creates new form tempeture_converter
     */
    public tempeture_converter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    String value1;
    String value2;
    String num;
    double ans;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("convert what quantity?");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "degree Celsius", "degree Fahrenheit", "degree Rankine", "degree Reaumur", "Kelvin" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "degree Celsius", "degree Fahrenheit", "degree Rankine", "degree Reaumur", "Kelvin" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("From:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("To:");

        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText(" ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText(" ");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jButton1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(48, 48, 48)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//get the entered value from text area
    private void enternum(String q){
     num = jTextField1.getText() + q;
    jTextField1.setText(num);
}
    //select whatb entered value
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       value1 = jComboBox1.getSelectedItem().toString();
           
    }//GEN-LAST:event_jComboBox1ActionPerformed
//select what unit to covert entered value 
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
       value2 = jComboBox2.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Double num = Double.parseDouble(String.valueOf(jTextField1.getText()));//first entered value convert to double data type and assign to num variable
        if(value1=="degree Celsius"){
           if(value2=="degree Celsius"){
                    ans = num;
                    jTextField2.setText(String.valueOf(num+" degree Celsius"+"="+ans+" degree Celsius"));
                    }else if(value2=="degree Fahrenheit"){
                    ans = (num*1.8)+32;
                     jTextField2.setText(String.valueOf(num+" degree Celsius"+"="+ans+" degree Fahrenheit"));
                    }else if(value2=="degree Rankine"){
                    ans = (num*1.8)+491.67;
                     jTextField2.setText(String.valueOf(num+" degree Celsius"+"="+ans+" degree Rankine"));
                    }else if(value2=="degree Reaumur"){
                    ans = (num*0.8);
                     jTextField2.setText(String.valueOf(num+" degree Celsius"+"="+ans+" degree Reaumur"));
                    }else{
                    ans = (num+273.15);
                    jTextField2.setText(String.valueOf(num+" degree Celsius"+"="+ans+" degree Kelvin"));
       }
       }
              if(value1=="degree Fahrenheit"){
                     double num1 = 5*(num-32)/9;//convert to celsius entered value
           if(value2=="degree Celsius"){
                    ans = num1;
                    jTextField2.setText(String.valueOf(num+" degree Fahrenheit"+"="+ans+" degree Celsius"));
                    }else if(value2=="degree Fahrenheit"){
                    ans = (num1*1.8)+32;
                     jTextField2.setText(String.valueOf(num+" degree Fahrenheit"+"="+ans+" degree Fahrenheit"));
                    }else if(value2=="degree Rankine"){
                    ans = (num1*1.8)+491.67;
                     jTextField2.setText(String.valueOf(num+" degree Fahrenheit"+"="+ans+" degree Rankine"));
                    }else if(value2=="degree Reaumur"){
                    ans = (num1*0.8);
                     jTextField2.setText(String.valueOf(num+" degree Fahrenheit"+"="+ans+" degree Reaumur"));
                    }else{
                    ans = (num1+273.15);
                    jTextField2.setText(String.valueOf(num+" degree Fahrenheit"+"="+ans+" degree Kelvin"));
       }
       }
                    if(value1=="degree Rankine"){
                           double num1 = 5*(num-491.67)/9;//convert to celsius entered value
           if(value2=="degree Celsius"){
                    ans = num1;
                    jTextField2.setText(String.valueOf(num+" degree Rankine"+"="+ans+" degree Celsius"));
                    }else if(value2=="degree Fahrenheit"){
                    ans = (num1*1.8)+32;
                     jTextField2.setText(String.valueOf(num+" degree Rankine"+"="+ans+" degree Fahrenheit"));
                    }else if(value2=="degree Rankine"){
                    ans = (num1*1.8)+491.67;
                     jTextField2.setText(String.valueOf(num+" degree Rankine"+"="+ans+" degree Rankine"));
                    }else if(value2=="degree Reaumur"){
                    ans = (num1*0.8);
                     jTextField2.setText(String.valueOf(num+" degree Rankine"+"="+ans+" degree Reaumur"));
                    }else{
                    ans = (num1+273.15);
                    jTextField2.setText(String.valueOf(num+" degree Rankine"+"="+ans+" degree Kelvin"));
       }
       }
         if(value1=="degree Reaumur"){
                double num1 = (num*1.25);//convert to celsius entered value
           if(value2=="degree Celsius"){
                    ans = num1;
                    jTextField2.setText(String.valueOf(num+" degree Reaumur"+"="+ans+" degree Celsius"));
                    }else if(value2=="degree Fahrenheit"){
                    ans = (num1*1.8)+32;
                     jTextField2.setText(String.valueOf(num+" degree Reaumur"+"="+ans+" degree Fahrenheit"));
                    }else if(value2=="degree Rankine"){
                    ans = (num1*1.8)+491.67;
                     jTextField2.setText(String.valueOf(num+" degree Reaumur"+"="+ans+" degree Rankine"));
                    }else if(value2=="degree Reaumur"){
                    ans = (num1*0.8);
                     jTextField2.setText(String.valueOf(num+" degree Reaumur"+"="+ans+" degree Reaumur"));
                    }else{
                    ans = (num1+273.15);
                    jTextField2.setText(String.valueOf(num+" degree Reaumur"+"="+ans+" degree Kelvin"));
       }
       }
        if(value1=="Kelvin"){
            double num1 = (num-273.15);//convert to celsius entered value
           if(value2=="degree Celsius"){
                    ans = num1;
                    jTextField2.setText(String.valueOf(num+" degree Kelvin"+"="+ans+" degree Celsius"));
                    }else if(value2=="degree Fahrenheit"){
                    ans = (num1*1.8)+32;
                     jTextField2.setText(String.valueOf(num+" degree Kelvin"+"="+ans+" degree Fahrenheit"));
                    }else if(value2=="degree Rankine"){
                    ans = (num1*1.8)+491.67;
                     jTextField2.setText(String.valueOf(num+" degree Kelvin"+"="+ans+" degree Rankine"));
                    }else if(value2=="degree Reaumur"){
                    ans = (num1*0.8);
                     jTextField2.setText(String.valueOf(num+" degree Kelvin"+"="+ans+" degree Reaumur"));
                    }else{
                    ans = (num1+273.15);
                    jTextField2.setText(String.valueOf(num+" degree Kelvin"+"="+ans+" degree Kelvin"));
       }
       }
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tempeture_converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tempeture_converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tempeture_converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tempeture_converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tempeture_converter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
